name: test-hello

on: 
  push:
    branches:
      - "master"

jobs:
  test:
    name: Execute Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
        
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_TAG: latest
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: IMAGE_NAME,IMAGE_TAG
          script: |
            docker pull $IMAGE_NAME:$IMAGE_TAG
            docker stop cobreaqui-container
            docker rm cobreaqui-container
            docker run --init -d --name cobreaqui-container $IMAGE_NAME:$IMAGE_TAG
            docker system prune -af